//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.12 at 04:26:37 PM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://entelect.training/incubator/spring-loyalty-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package entelect.training.incubator.spring.booking.service.loyalty;
